[package]
name = "max2sc-core"
version = "0.1.0"
edition = "2021"
description = "Core types and traits for max2sc converter"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }